# Generated by Django 4.2.7 on 2023-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypes',
            name='names_count',
            field=models.SmallIntegerField(),
        ),
    ]
