# Generated by Django 5.0 on 2023-12-16 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventtypes_names_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bride_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='', upload_to='events/cover'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='groom_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.eventtypes'),
        ),
        migrations.AlterField(
            model_name='eventnames',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
