# Generated by Django 5.0 on 2023-12-16 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_bride_name_event_cover_image_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.eventtypes'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('album_cover', models.ImageField(upload_to='event/gallery/collection')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='CroppedGalleryFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event/gallery/faces/')),
                ('face_locations', models.JSONField(null=True)),
                ('face_embedding', models.JSONField(null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.galleryimage')),
            ],
        ),
        migrations.DeleteModel(
            name='EventNames',
        ),
    ]
