# Generated by Django 5.0 on 2023-12-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_galleryimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='croppedgalleryface',
            name='image',
            field=models.ImageField(upload_to='events/gallery/faces/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='album_cover',
            field=models.ImageField(upload_to='events/gallery/collection'),
        ),
    ]
