# Generated by Django 5.0 on 2023-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_galleryimage_is_processed_galleryimage_is_processing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelfieRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=24)),
                ('email_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('selfie_image', models.ImageField(upload_to='user_selfies')),
                ('selfie_embedding', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='croppedgalleryface',
            name='face_embedding',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='croppedgalleryface',
            name='face_locations',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
