# Generated by Django 5.0 on 2023-12-16 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userdesignation'),
        ),
    ]
